package com.asif.attendance;
import java.sql.*;import java.util.Scanner;
public class AttendanceApp{
 static final Scanner sc=new Scanner(System.in);
 static final String URL=System.getenv().getOrDefault("DB_URL","jdbc:mysql://localhost:3306/attendance_db");
 static final String USER=System.getenv().getOrDefault("DB_USER","root"),PASS=System.getenv().getOrDefault("DB_PASSWORD","");
 public static void main(String[]a){while(true){System.out.println("\n1 Add employee  2 Mark attendance  3 View attendance  4 Update employee  5 Delete employee  0 Exit");String ch=sc.nextLine();try{switch(ch){case"1"->addEmployee();case"2"->markAttendance();case"3"->viewAttendance();case"4"->updateEmployee();case"5"->deleteEmployee();case"0"->{return;}default->System.out.println("Choose a valid option.");}}catch(SQLException e){System.out.println("Database error: "+e.getMessage());}}}
 static Connection connect()throws SQLException{return DriverManager.getConnection(URL,USER,PASS);}
 static void addEmployee()throws SQLException{System.out.print("Name: ");String n=sc.nextLine();System.out.print("Department: ");String d=sc.nextLine();try(Connection c=connect();PreparedStatement p=c.prepareStatement("INSERT INTO employees(name,department) VALUES(?,?)")){p.setString(1,n);p.setString(2,d);p.executeUpdate();System.out.println("Employee added.");}}
 static void markAttendance()throws SQLException{System.out.print("Employee ID: ");int id=Integer.parseInt(sc.nextLine());System.out.print("Date (YYYY-MM-DD): ");String date=sc.nextLine();System.out.print("Status (PRESENT/ABSENT): ");String s=sc.nextLine().toUpperCase();try(Connection c=connect();PreparedStatement p=c.prepareStatement("INSERT INTO attendance(employee_id,attendance_date,status) VALUES(?,?,?)")){p.setInt(1,id);p.setDate(2,Date.valueOf(date));p.setString(3,s);p.executeUpdate();System.out.println("Attendance saved.");}}
 static void viewAttendance()throws SQLException{String q="SELECT e.id,e.name,e.department,a.attendance_date,a.status FROM employees e JOIN attendance a ON e.id=a.employee_id ORDER BY a.attendance_date DESC";try(Connection c=connect();PreparedStatement p=c.prepareStatement(q);ResultSet r=p.executeQuery()){while(r.next())System.out.printf("%d | %s | %s | %s | %s%n",r.getInt(1),r.getString(2),r.getString(3),r.getDate(4),r.getString(5));}}
 static void updateEmployee()throws SQLException{System.out.print("Employee ID: ");int id=Integer.parseInt(sc.nextLine());System.out.print("New department: ");String d=sc.nextLine();try(Connection c=connect();PreparedStatement p=c.prepareStatement("UPDATE employees SET department=? WHERE id=?")){p.setString(1,d);p.setInt(2,id);System.out.println(p.executeUpdate()>0?"Updated.":"Employee not found.");}}
 static void deleteEmployee()throws SQLException{System.out.print("Employee ID: ");int id=Integer.parseInt(sc.nextLine());try(Connection c=connect();PreparedStatement p=c.prepareStatement("DELETE FROM employees WHERE id=?")){p.setInt(1,id);System.out.println(p.executeUpdate()>0?"Deleted.":"Employee not found.");}}
}